import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppButton, Badge, EmptyState, FormField, RideCard, ScreenHeader } from "../components/ui";
import { colors, radius, shadows, spacing, typography } from "../theme";

export function HomeScreen({ user, rides, bookings, onOpenRide, onNavigate }) {
	const nextRide = rides.find((ride) => ride.status === "open");
	const pending = bookings.filter((booking) => booking.driverId === user.id && booking.status === "pending").length;
	return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
		<View style={styles.homeTop}>
			<View><Text style={styles.eyebrow}>OLÁ, {user.name.split(" ")[0].toUpperCase()}</Text><Text style={styles.homeTitle}>Para onde vamos hoje?</Text></View>
			<View style={styles.avatar}><Text style={styles.avatarText}>{user.name.charAt(0)}</Text></View>
		</View>
		<Pressable onPress={() => onNavigate("search")} style={styles.searchShortcut}><MaterialCommunityIcons name="magnify" size={22} color={colors.textSecondary} /><Text style={styles.searchPlaceholder}>De onde você quer sair?</Text><View style={styles.filterIcon}><MaterialCommunityIcons name="tune-variant" size={20} color="#fff" /></View></Pressable>
		<View style={styles.heroCard}>
			<View style={styles.heroContent}><Badge text="COMUNIDADE ICEA" tone="success" /><Text style={styles.heroTitle}>Divida o caminho, multiplique boas histórias.</Text><Text style={styles.heroText}>Economize e reduza o trânsito compartilhando sua rota.</Text></View>
			<MaterialCommunityIcons name="car-connected" size={72} color="#93C5FD" />
		</View>
		<Text style={styles.sectionTitle}>Acesso rápido</Text>
		<View style={styles.quickGrid}>
			<QuickAction icon="magnify" label="Buscar carona" color={colors.primary} onPress={() => onNavigate("search")} />
			<QuickAction icon="plus-circle-outline" label="Oferecer carona" color={colors.accentDark} onPress={() => onNavigate("publish")} />
			<QuickAction icon="calendar-check-outline" label="Minhas viagens" color="#7C3AED" onPress={() => onNavigate("trips")} badge={pending} />
		</View>
		<View style={styles.sectionRow}><Text style={styles.sectionTitle}>Próximas caronas</Text><Pressable onPress={() => onNavigate("search")}><Text style={styles.link}>Ver todas</Text></Pressable></View>
		{nextRide ? <RideCard ride={nextRide} onPress={onOpenRide} /> : <EmptyState title="Nenhuma carona agora" text="Publique uma rota e ajude a comunidade." />}
	</ScrollView>;
}

function QuickAction({ icon, label, color, onPress, badge }) {
	return <Pressable onPress={onPress} style={({ pressed }) => [styles.quick, pressed && styles.pressed]}><View style={[styles.quickIcon, { backgroundColor: `${color}18` }]}><MaterialCommunityIcons name={icon} size={26} color={color} /></View><Text style={styles.quickText}>{label}</Text>{badge > 0 && <View style={styles.counter}><Text style={styles.counterText}>{badge}</Text></View>}</Pressable>;
}

export function SearchScreen({ rides, onOpenRide }) {
	const [origin, setOrigin] = useState("");
	const [destination, setDestination] = useState("");
	const filtered = useMemo(() => rides.filter((ride) => ride.status === "open" && ride.seatsAvailable > 0 && ride.origin.toLowerCase().includes(origin.toLowerCase()) && ride.destination.toLowerCase().includes(destination.toLowerCase())), [rides, origin, destination]);
	return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
		<ScreenHeader title="Buscar caronas" subtitle="Encontre uma rota que combine com você" />
		<View style={styles.searchCard}>
			<FormField label="Saindo de" icon="map-marker-outline" placeholder="Ex.: Centro" value={origin} onChangeText={setOrigin} />
			<FormField label="Indo para" icon="flag-checkered" placeholder="Ex.: ICEA / UFOP" value={destination} onChangeText={setDestination} />
			<View style={styles.filterRow}><Badge text="Qualquer data" /><Badge text="Qualquer horário" /><Pressable onPress={() => { setOrigin(""); setDestination(""); }}><Text style={styles.link}>Limpar</Text></Pressable></View>
		</View>
		<Text style={styles.resultCount}>{filtered.length} carona{filtered.length !== 1 ? "s" : ""} encontrada{filtered.length !== 1 ? "s" : ""}</Text>
		{filtered.map((ride) => <RideCard key={ride.id} ride={ride} onPress={onOpenRide} />)}
		{!filtered.length && <EmptyState icon="map-search-outline" title="Nenhuma rota encontrada" text="Tente buscar por outro local ou limpe os filtros." action={<AppButton title="Limpar filtros" variant="secondary" onPress={() => { setOrigin(""); setDestination(""); }} />} />}
	</ScrollView>;
}

export function PublishScreen({ onPublish }) {
	const blank = { origin: "", destination: "ICEA / UFOP", date: "", time: "", seats: "3", price: "5,00", vehicle: "", rules: "" };
	const [form, setForm] = useState(blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
	const set = (key, value) => { setForm((old) => ({ ...old, [key]: value })); setError(""); };
	async function submit() {
		if (!form.origin.trim() || !form.destination.trim() || !form.date.trim() || !form.time.trim()) return setError("Preencha origem, destino, data e horário.");
		if (!Number(form.seats) || Number(form.seats) < 1) return setError("Informe pelo menos uma vaga.");
		setSaving(true);
		const result = await onPublish(form);
		setSaving(false);
		if (result) return setError(result);
		setForm(blank); Alert.alert("Carona publicada!", "Sua rota já está disponível para a comunidade.");
	}
	return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
		<ScreenHeader title="Oferecer carona" subtitle="Compartilhe sua rota com a comunidade" />
		{error ? <View style={styles.alert}><MaterialCommunityIcons name="alert-circle-outline" size={20} color={colors.error} /><Text style={styles.alertText}>{error}</Text></View> : null}
		<View style={styles.formCard}>
			<Text style={styles.formSection}>Rota</Text><FormField label="Origem" icon="map-marker-outline" placeholder="Local de partida" value={form.origin} onChangeText={(v) => set("origin", v)} /><FormField label="Destino" icon="flag-checkered" value={form.destination} onChangeText={(v) => set("destination", v)} />
			<Text style={styles.formSection}>Quando</Text><View style={styles.twoColumns}><FormField style={styles.column} label="Data" icon="calendar-outline" placeholder="DD/MM/AAAA" keyboardType="numeric" value={form.date} onChangeText={(v) => set("date", v)} /><FormField style={styles.column} label="Horário" icon="clock-outline" placeholder="HH:MM" keyboardType="numeric" value={form.time} onChangeText={(v) => set("time", v)} /></View>
			<Text style={styles.formSection}>Detalhes</Text><View style={styles.twoColumns}><FormField style={styles.column} label="Vagas" icon="seat-passenger" keyboardType="number-pad" value={form.seats} onChangeText={(v) => set("seats", v)} /><FormField style={styles.column} label="Preço por pessoa" icon="cash" keyboardType="decimal-pad" value={form.price} onChangeText={(v) => set("price", v)} /></View>
			<FormField label="Veículo" icon="car-outline" placeholder="Ex.: Fiat Argo • Prata" value={form.vehicle} onChangeText={(v) => set("vehicle", v)} /><FormField label="Regras (opcional)" icon="text-box-outline" placeholder="Ex.: Não fumar" multiline value={form.rules} onChangeText={(v) => set("rules", v)} />
			<AppButton title={saving ? "Publicando..." : "Publicar carona"} disabled={saving} icon="check" onPress={submit} />
		</View>
	</ScrollView>;
}

export function TripsScreen({ user, rides, bookings, onOpenRide, onBookingStatus, onComplete }) {
	const [mode, setMode] = useState("rides");
	const myRides = rides.filter((ride) => ride.driverId === user.id);
	const myBookings = bookings.filter((booking) => booking.passengerId === user.id);
	const requests = bookings.filter((booking) => booking.driverId === user.id && booking.status === "pending");
	return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
		<ScreenHeader title="Minhas viagens" subtitle="Acompanhe caronas e solicitações" />
		<View style={styles.segment}>{[["rides", "Minhas caronas"], ["bookings", "Reservas"], ["requests", `Solicitações${requests.length ? ` (${requests.length})` : ""}`]].map(([key, label]) => <Pressable key={key} onPress={() => setMode(key)} style={[styles.segmentItem, mode === key && styles.segmentActive]}><Text style={[styles.segmentText, mode === key && styles.segmentTextActive]}>{label}</Text></Pressable>)}</View>
		{mode === "rides" && <>{myRides.map((ride) => <View key={ride.id}><RideCard ride={ride} onPress={onOpenRide} />{ride.status === "open" && <AppButton title="Marcar como concluída" variant="secondary" icon="flag-checkered" onPress={() => onComplete(ride.id)} style={styles.cardAction} />}{ride.status === "completed" && <Badge text="Viagem concluída" tone="success" />}</View>)}{!myRides.length && <EmptyState title="Você ainda não publicou" text="Ofereça uma carona para começar." />}</>}
		{mode === "bookings" && <>{myBookings.map((booking) => <BookingCard key={booking.id} booking={booking} ride={rides.find((r) => r.id === booking.rideId)} onPress={onOpenRide} />)}{!myBookings.length && <EmptyState icon="ticket-confirmation-outline" title="Nenhuma reserva" text="Ao solicitar uma vaga, ela aparecerá aqui." />}</>}
		{mode === "requests" && <>{requests.map((booking) => <View key={booking.id} style={styles.requestCard}><View style={styles.requestTop}><View style={styles.avatarSmall}><Text style={styles.avatarText}>{booking.passengerName.charAt(0)}</Text></View><View style={styles.grow}><Text style={styles.cardTitle}>{booking.passengerName}</Text><Text style={styles.muted}>solicitou uma vaga na sua carona</Text></View></View><View style={styles.requestActions}><AppButton title="Recusar" variant="secondary" onPress={() => onBookingStatus(booking.id, "rejected")} style={styles.flexButton} /><AppButton title="Aceitar" icon="check" onPress={() => onBookingStatus(booking.id, "accepted")} style={styles.flexButton} /></View></View>)}{!requests.length && <EmptyState icon="account-clock-outline" title="Tudo em dia" text="Você não tem solicitações pendentes." />}</>}
	</ScrollView>;
}

function BookingCard({ booking, ride, onPress }) { const labels = { pending: ["Aguardando motorista", "warning"], accepted: ["Reserva confirmada", "success"], rejected: ["Solicitação recusada", "error"], cancelled: ["Cancelada", "error"] }; const status = labels[booking.status] || labels.pending; return <Pressable disabled={!ride} onPress={() => onPress(ride)} style={({ pressed }) => [styles.requestCard, pressed && styles.pressed]}><View style={styles.sectionRow}><Text style={styles.cardTitle}>{ride ? `${ride.origin} → ${ride.destination}` : "Carona"}</Text><Badge text={status[0]} tone={status[1]} /></View>{ride && <View style={styles.sectionRow}><Text style={styles.muted}>{ride.date} às {ride.time}</Text><Text style={styles.link}>Ver detalhes</Text></View>}</Pressable>; }

export function ProfileScreen({ user, onAbout, onAdmin, onLogout }) {
	const roles = user.roles.map((r) => r === "driver" ? "Motorista" : "Passageiro").join(" e ");
	return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
		<ScreenHeader title="Meu perfil" subtitle="Seus dados e preferências" />
		<View style={styles.profileCard}><View style={styles.profileAvatar}><Text style={styles.profileInitial}>{user.name.charAt(0)}</Text></View><Text style={styles.profileName}>{user.name}</Text><Text style={styles.muted}>{user.email}</Text><Badge text={roles} tone="success" /><View style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>{user.rating || "—"}</Text><Text style={styles.statLabel}>avaliação</Text></View><View style={styles.divider} /><View style={styles.stat}><Text style={styles.statValue}>{user.trips || 0}</Text><Text style={styles.statLabel}>viagens</Text></View><View style={styles.divider} /><View style={styles.stat}><Text style={styles.statValue}>100%</Text><Text style={styles.statLabel}>verificado</Text></View></View></View>
		<View style={styles.menuCard}><MenuItem icon="account-edit-outline" label="Editar perfil" onPress={() => Alert.alert("Perfil", "Edição disponível na versão integrada ao Firebase.")} /><MenuItem icon="shield-check-outline" label="Segurança e privacidade" onPress={() => Alert.alert("Privacidade", "Seus dados são usados apenas para viabilizar as caronas.")} /><MenuItem icon="information-outline" label="Sobre o aplicativo" onPress={onAbout} />{user.isAdmin && <MenuItem icon="shield-account-outline" label="Painel administrativo" onPress={onAdmin} accent />}</View>
		<AppButton title="Sair da conta" icon="logout" variant="secondary" onPress={onLogout} />
	</ScrollView>;
}

function MenuItem({ icon, label, onPress, accent }) { return <Pressable onPress={onPress} style={styles.menuItem}><View style={[styles.menuIcon, accent && { backgroundColor: "#FEF3C7" }]}><MaterialCommunityIcons name={icon} size={22} color={accent ? "#A16207" : colors.primary} /></View><Text style={styles.menuLabel}>{label}</Text><MaterialCommunityIcons name="chevron-right" size={22} color={colors.textSecondary} /></Pressable>; }

export function RideDetailsScreen({ ride, currentUser, booking, onBack, onReserve, onReport, onCancel, onRate }) {
	const isOwner = ride.driverId === currentUser.id; const isCompleted = ride.status === "completed";
	return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
		<ScreenHeader title="Detalhes da carona" onBack={onBack} action={<Pressable onPress={onReport} style={styles.headerAction}><MaterialCommunityIcons name="alert-outline" size={22} color={colors.error} /></Pressable>} />
		<View style={styles.detailRoute}><View style={styles.detailDate}><MaterialCommunityIcons name="calendar" size={22} color={colors.primary} /><Text style={styles.detailDateText}>{ride.date} • {ride.time}</Text></View><View style={styles.detailStop}><View style={styles.originDot} /><View><Text style={styles.stopLabel}>SAÍDA</Text><Text style={styles.stopName}>{ride.origin}</Text></View></View><View style={styles.detailConnector} /><View style={styles.detailStop}><MaterialCommunityIcons name="map-marker" size={19} color={colors.accentDark} /><View><Text style={styles.stopLabel}>DESTINO</Text><Text style={styles.stopName}>{ride.destination}</Text></View></View></View>
		<View style={styles.driverCard}><View style={styles.profileAvatarSmall}><Text style={styles.avatarText}>{ride.driverName.charAt(0)}</Text></View><View style={styles.grow}><Text style={styles.cardTitle}>{ride.driverName}</Text><View style={styles.inline}><MaterialCommunityIcons name="star" size={16} color={colors.warning} /><Text style={styles.muted}>{ride.driverRating} • Motorista verificado</Text></View></View></View>
		<View style={styles.detailGrid}><Detail icon="seat-passenger" value={`${ride.seatsAvailable} vagas`} label="disponíveis" /><Detail icon="cash" value={`R$ ${Number(ride.price).toFixed(2).replace(".", ",")}`} label="por pessoa" /><Detail icon="car-outline" value={ride.vehicle || "Não informado"} label="veículo" wide /></View>
		<View style={styles.infoCard}><Text style={styles.cardTitle}>Regras e observações</Text><Text style={styles.bodyText}>{ride.rules || "Nenhuma observação informada."}</Text></View>
		{isOwner ? <><Badge text="Esta carona foi publicada por você" tone="info" />{!isCompleted && <AppButton title="Cancelar carona" variant="danger" icon="close" onPress={onCancel} style={styles.topSpace} />}</> : isCompleted ? <AppButton title="Avaliar motorista" icon="star-outline" onPress={onRate} /> : booking ? <View style={styles.bookingNotice}><MaterialCommunityIcons name="clock-check-outline" size={22} color={colors.primary} /><Text style={styles.bookingNoticeText}>{booking.status === "pending" ? "Solicitação enviada. Aguarde o motorista." : booking.status === "accepted" ? "Sua reserva está confirmada!" : "Esta solicitação não está ativa."}</Text></View> : <AppButton disabled={ride.seatsAvailable < 1} title={ride.seatsAvailable < 1 ? "Carona lotada" : "Solicitar uma vaga"} icon="seat-passenger" onPress={onReserve} />}
	</ScrollView>;
}

function Detail({ icon, value, label, wide }) { return <View style={[styles.detailItem, wide && styles.detailWide]}><MaterialCommunityIcons name={icon} size={23} color={colors.primary} /><View><Text style={styles.detailValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View></View>; }

export function ReportScreen({ targetName, onBack, onSubmit }) {
	const [reason, setReason] = useState("Comportamento inadequado"); const [details, setDetails] = useState("");
	return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><ScreenHeader title="Fazer denúncia" subtitle={`Sobre ${targetName}`} onBack={onBack} /><View style={styles.warningBox}><MaterialCommunityIcons name="shield-alert-outline" size={25} color="#A16207" /><Text style={styles.warningText}>Denúncias são analisadas pela administração. Descreva apenas fatos verdadeiros.</Text></View><Text style={styles.label}>Motivo</Text><View style={styles.reasonList}>{["Comportamento inadequado", "Não compareceu", "Informação falsa", "Outro"].map((item) => <Pressable key={item} onPress={() => setReason(item)} style={[styles.reason, reason === item && styles.reasonActive]}><MaterialCommunityIcons name={reason === item ? "radiobox-marked" : "radiobox-blank"} size={21} color={reason === item ? colors.primary : colors.textSecondary} /><Text style={styles.reasonText}>{item}</Text></Pressable>)}</View><FormField label="Conte o que aconteceu" placeholder="Inclua informações que ajudem na análise..." multiline numberOfLines={5} value={details} onChangeText={setDetails} /><AppButton title="Enviar denúncia" variant="danger" icon="alert-outline" disabled={!details.trim()} onPress={() => onSubmit({ reason, details })} /></ScrollView>;
}

export function RatingScreen({ targetName, onBack, onSubmit }) { const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); return <ScrollView contentContainerStyle={styles.page}><ScreenHeader title="Avaliar viagem" subtitle={`Como foi viajar com ${targetName}?`} onBack={onBack} /><View style={styles.ratingCard}><MaterialCommunityIcons name="account-heart-outline" size={52} color={colors.primary} /><Text style={styles.ratingTitle}>{rating ? ["", "Ruim", "Regular", "Boa", "Muito boa", "Excelente!"][rating] : "Toque para avaliar"}</Text><View style={styles.stars}>{[1,2,3,4,5].map((star) => <Pressable key={star} onPress={() => setRating(star)} hitSlop={6}><MaterialCommunityIcons name={star <= rating ? "star" : "star-outline"} size={42} color={colors.warning} /></Pressable>)}</View></View><FormField label="Comentário (opcional)" placeholder="Conte como foi sua experiência..." multiline value={comment} onChangeText={setComment} /><AppButton title="Enviar avaliação" icon="check" disabled={!rating} onPress={() => onSubmit({ rating, comment })} /></ScrollView>; }

export function AboutScreen({ onBack }) { return <ScrollView contentContainerStyle={styles.page}><ScreenHeader title="Sobre" onBack={onBack} /><View style={styles.aboutHero}><View style={styles.aboutIcon}><MaterialCommunityIcons name="car-multiple" size={42} color="#fff" /></View><Text style={styles.aboutTitle}>Caronas ICEA</Text><Text style={styles.muted}>Versão 1.0.0 • Projeto acadêmico</Text></View><View style={styles.infoCard}><Text style={styles.cardTitle}>Nossa proposta</Text><Text style={styles.bodyText}>Conectar motoristas e passageiros da comunidade ICEA/UFOP que compartilham rotas e horários, oferecendo transporte mais econômico, sustentável e seguro.</Text></View><View style={styles.infoCard}><Text style={styles.cardTitle}>Desenvolvido por</Text><Text style={styles.bodyText}>Preencha os nomes e matrículas dos integrantes no arquivo README.md antes da entrega.</Text></View><View style={styles.infoCard}><Text style={styles.cardTitle}>Tecnologias</Text><Text style={styles.bodyText}>React Native • Expo • JavaScript</Text></View></ScrollView>; }

export function AdminScreen({ reports, users, onBack, onResolve, onToggleBlock }) { const [tab, setTab] = useState("reports"); return <ScrollView contentContainerStyle={styles.page}><ScreenHeader title="Administração" subtitle="Moderação da comunidade" onBack={onBack} /><View style={styles.adminBanner}><MaterialCommunityIcons name="shield-account" size={35} color="#A16207" /><View><Text style={styles.cardTitle}>Área restrita</Text><Text style={styles.muted}>Ações de moderação ficam registradas.</Text></View></View><View style={styles.segment}>{[["reports", "Denúncias"], ["users", "Usuários"]].map(([key,label]) => <Pressable key={key} onPress={() => setTab(key)} style={[styles.segmentItem, tab === key && styles.segmentActive]}><Text style={[styles.segmentText, tab === key && styles.segmentTextActive]}>{label}</Text></Pressable>)}</View>{tab === "reports" ? reports.map((report) => <View key={report.id} style={styles.requestCard}><View style={styles.sectionRow}><Text style={styles.cardTitle}>{report.reason}</Text><Badge text={report.status === "pending" ? "Pendente" : "Resolvida"} tone={report.status === "pending" ? "warning" : "success"} /></View><Text style={styles.muted}>Denunciado: {report.targetName}</Text><Text style={styles.bodyText}>{report.details}</Text>{report.status === "pending" && <AppButton title="Marcar como resolvida" variant="secondary" onPress={() => onResolve(report.id)} />}</View>) : users.map((item) => <View key={item.id} style={styles.requestCard}><View style={styles.sectionRow}><View><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.muted}>{item.email}</Text></View><Badge text={item.isBlocked ? "Bloqueado" : "Ativo"} tone={item.isBlocked ? "error" : "success"} /></View>{!item.isAdmin && <AppButton title={item.isBlocked ? "Desbloquear usuário" : "Bloquear usuário"} variant={item.isBlocked ? "secondary" : "danger"} onPress={() => onToggleBlock(item.id)} />}</View>)}</ScrollView>; }

const styles = StyleSheet.create({
	page: { paddingHorizontal: spacing.lg, paddingBottom: 120, width: "100%", maxWidth: 720, alignSelf: "center" }, grow: { flex: 1 }, pressed: { opacity: .7 }, inline: { flexDirection: "row", alignItems: "center", gap: 5 }, muted: { ...typography.caption, color: colors.textSecondary }, bodyText: { ...typography.body, color: colors.textSecondary, marginTop: 8 }, label: { ...typography.label, color: colors.text, marginBottom: 8 }, link: { ...typography.label, color: colors.primary },
	homeTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 18, marginBottom: 22 }, eyebrow: { ...typography.caption, color: colors.primary, fontWeight: "800", letterSpacing: 1 }, homeTitle: { ...typography.title, color: colors.text, marginTop: 3 }, avatar: { width: 50, height: 50, borderRadius: 18, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, avatarText: { ...typography.subtitle, color: colors.primaryDark, fontWeight: "800" }, searchShortcut: { minHeight: 58, flexDirection: "row", alignItems: "center", paddingLeft: 16, gap: 10, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.small }, searchPlaceholder: { ...typography.body, color: colors.textSecondary, flex: 1 }, filterIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginRight: 7 },
	heroCard: { minHeight: 165, flexDirection: "row", alignItems: "center", overflow: "hidden", backgroundColor: "#172554", borderRadius: radius.xl, padding: 20, marginVertical: 22 }, heroContent: { flex: 1, alignItems: "flex-start" }, heroTitle: { ...typography.subtitle, color: "#fff", marginTop: 12 }, heroText: { ...typography.caption, color: "#CBD5E1", marginTop: 6 }, sectionTitle: { ...typography.subtitle, color: colors.text }, quickGrid: { flexDirection: "row", gap: 10, marginTop: 12, marginBottom: 25 }, quick: { flex: 1, minHeight: 118, alignItems: "center", justifyContent: "center", gap: 8, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 8, ...shadows.small }, quickIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 16 }, quickText: { ...typography.caption, fontWeight: "700", color: colors.text, textAlign: "center" }, counter: { position: "absolute", right: 8, top: 8, minWidth: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: colors.error }, counterText: { ...typography.caption, color: "#fff", fontWeight: "800" }, sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12, marginTop: 8, marginBottom: 12 },
	searchCard: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: 18, borderWidth: 1, borderColor: colors.border, ...shadows.small }, filterRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 }, resultCount: { ...typography.label, color: colors.textSecondary, marginVertical: 20 }, formCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, padding: 18 }, formSection: { ...typography.subtitle, color: colors.text, marginBottom: 14, marginTop: 5 }, twoColumns: { flexDirection: "row", gap: 10 }, column: { flex: 1 }, alert: { flexDirection: "row", gap: 8, padding: 12, borderRadius: radius.md, backgroundColor: "#FFF1F2", marginBottom: 12 }, alertText: { ...typography.caption, color: colors.error, flex: 1 },
	segment: { flexDirection: "row", padding: 4, borderRadius: radius.md, backgroundColor: colors.surfaceMuted, marginBottom: 20 }, segmentItem: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", paddingHorizontal: 4, borderRadius: 9 }, segmentActive: { backgroundColor: colors.surface, ...shadows.small }, segmentText: { ...typography.caption, fontWeight: "600", color: colors.textSecondary, textAlign: "center" }, segmentTextActive: { color: colors.primary }, requestCard: { padding: 17, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginBottom: 12 }, requestTop: { flexDirection: "row", gap: 11, alignItems: "center" }, avatarSmall: { width: 42, height: 42, borderRadius: 15, backgroundColor: colors.primaryLight, alignItems: "center", justifyContent: "center" }, cardTitle: { ...typography.label, fontSize: 16, color: colors.text }, requestActions: { flexDirection: "row", gap: 9, marginTop: 15 }, flexButton: { flex: 1, minHeight: 46 }, cardAction: { marginTop: -5, marginBottom: 18 },
	profileCard: { alignItems: "center", padding: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, ...shadows.small }, profileAvatar: { width: 88, height: 88, borderRadius: 30, alignItems: "center", justifyContent: "center", backgroundColor: colors.primaryLight, marginBottom: 12 }, profileInitial: { fontSize: 38, fontWeight: "800", color: colors.primary }, profileName: { ...typography.subtitle, color: colors.text, marginBottom: 2 }, stats: { flexDirection: "row", alignItems: "center", alignSelf: "stretch", marginTop: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.border }, stat: { flex: 1, alignItems: "center" }, statValue: { ...typography.subtitle, color: colors.text }, statLabel: { ...typography.caption, color: colors.textSecondary }, divider: { width: 1, height: 35, backgroundColor: colors.border }, menuCard: { borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginVertical: 18, overflow: "hidden" }, menuItem: { minHeight: 65, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, menuIcon: { width: 39, height: 39, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.primaryLight }, menuLabel: { ...typography.body, color: colors.text, flex: 1 },
	headerAction: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#FFF1F2" }, detailRoute: { padding: 20, borderRadius: radius.xl, backgroundColor: "#EFF6FF", marginBottom: 14 }, detailDate: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 21 }, detailDateText: { ...typography.label, color: colors.primaryDark }, detailStop: { flexDirection: "row", alignItems: "flex-start", gap: 12 }, originDot: { width: 12, height: 12, borderRadius: 6, borderWidth: 3, borderColor: colors.primary, margin: 3 }, stopLabel: { ...typography.caption, fontSize: 11, color: colors.textSecondary, fontWeight: "700" }, stopName: { ...typography.body, color: colors.text, fontWeight: "700" }, detailConnector: { height: 26, width: 2, backgroundColor: "#93C5FD", marginLeft: 6 }, driverCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 17, backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, marginBottom: 14 }, profileAvatarSmall: { width: 52, height: 52, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.primaryLight }, detailGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 14 }, detailItem: { width: "48%", flexDirection: "row", alignItems: "center", gap: 10, padding: 15, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, detailWide: { width: "100%" }, detailValue: { ...typography.label, color: colors.text }, infoCard: { padding: 18, backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, marginBottom: 14 }, topSpace: { marginTop: 15 }, bookingNotice: { flexDirection: "row", gap: 10, alignItems: "center", padding: 16, borderRadius: radius.md, backgroundColor: colors.primaryLight }, bookingNoticeText: { ...typography.label, color: colors.primaryDark, flex: 1 },
	warningBox: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, borderRadius: radius.md, backgroundColor: "#FEF3C7", marginBottom: 20 }, warningText: { ...typography.caption, color: "#854D0E", flex: 1 }, reasonList: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: "hidden", marginBottom: 18 }, reason: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.surface }, reasonActive: { backgroundColor: colors.primaryLight }, reasonText: { ...typography.body, color: colors.text }, ratingCard: { alignItems: "center", padding: 28, backgroundColor: colors.surface, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.border, marginBottom: 20 }, ratingTitle: { ...typography.subtitle, color: colors.text, marginVertical: 15 }, stars: { flexDirection: "row", gap: 5 },
	aboutHero: { alignItems: "center", padding: 25 }, aboutIcon: { width: 80, height: 80, borderRadius: 26, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginBottom: 13 }, aboutTitle: { ...typography.title, color: colors.text }, adminBanner: { flexDirection: "row", gap: 12, alignItems: "center", padding: 16, backgroundColor: "#FEF3C7", borderRadius: radius.lg, marginBottom: 16 }
});
